---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kiran-youtube-app
  namespace: my-app
  labels:
    app: kiran-youtube-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kiran-youtube-app
  template:
    metadata:
      labels:
        app: kiran-youtube-app
    spec:
      containers:
      - name: kiran-youtube-app
        image: "kiranpkdocker/kiran-youtube-app:latest"
        ports:
          - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: kiran-youtube-app
  namespace: my-app
spec:
  selector:
    app: kiran-youtube-app
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 8082
    port: 80
               
